run:
  concurrency: 4
  timeout: 5m

linters:
  disable-all: true
  # TODO: fix issues and enable linters.
  enable:
    - deadcode
    - depguard
    - errcheck
    - exportloopref
#    - gci
#    - goconst
#    - gocritic
    - gocyclo
#    - gofmt
#    - goimports
#    - gosec
#    - gosimple
    - govet
    - ineffassign
#    - misspell
    - nakedret
    - prealloc
#    - revive
#    - staticcheck
    - structcheck
#    - stylecheck
    - typecheck
    - unconvert
#    - unparam
    - unused
    - varcheck

linters-settings:
  goimports:
    local-prefixes: github.com/hypnoglow/dotbro

issues:
#  exclude-rules:
#    - linters:
#        - golint
#      text: type name will be used as monitor.MonitorOption
