# Reference: https://golangci-lint.run/docs/configuration/file/

version: "2"

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - errchkjson
    - funcorder
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gomoddirectives
    - goprintffuncname
    # - gosec
    - govet
    - ineffassign
    - mirror
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    # - revive
    # - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace

  settings:
    gocritic:
      disabled-checks:
        - singleCaseSwitch
    gomoddirectives:
      toolchain-forbidden: true
    nolintlint:
      require-specific: true
      require-explanation: true

  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Relax requirements for tests.
      - linters:
          - goconst
          - noctx
        path: _test.go

formatters:
  enable:
    - gci
    - gofmt

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/hypnoglow/dotbro)

issues:
  fix: true

run:
  timeout: 5m
  build-tags: []
