name: Main
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  verify:
    name: Verify module
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install dependencies
        run: |
          go mod download

      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.41.1

      - name: Run tests
        run: |
          go test -v ./...
